recipes:
  - web
  - monitor
user: kyoko
tz: jst
rbenv:
  versions:
    - 2.2.2
  global: 2.2.2
  gems:
    - name: bundler
nginx:
  site_conf_template: ikyusan-api.conf.erb
  document_root: /var/www
  document_root_user: kyoko
  application: ikyusan-api
  server_name: ikyusan.sekahama.club
  port: 80
  unicorn_sock: /var/www/ikyusan-api/current/tmp/sockets/ikyusan-api_unicorn.sock
logrotate:
  app_log_dir: /var/www/ikyusan-api/shared/log
  rotate: 1
