user: kyoko
tz: jst
rbenv:
  versions:
    - 2.2.2
  global: 2.2.2
  gems:
    - name: bundler
nginx:
  site_conf_template: ikyusan-api.conf.erb
  document_root: /var/www
  document_root_user: ec2-user
  application: ikyusan-api
  server_name: localhost
  port: 80
  unicorn_sock: /var/www/ikyusan-api/current/tmp/sockets/ikyusan-api_unicorn.sock
