recipes:
  - web
  - db
  - monitor
user: kyoko
tz: jst
rbenv:
  versions:
    - 2.2.3
  global: 2.2.3
  gems:
    - name: bundler
    - name: mgem
mruby:
  version: 1.1.0
  mgems:
    - mruby-json
    - mruby-env
h2o:
  domain: ikyusan.sekahama.club
  application: ikyusan-api
  unix_sock_file_path: /var/www/ikyusan.sekahama.club/ikyusan-api/current/tmp/sockets/ikyusan-api_unicorn.sock
  document_root: /var/www/ikyusan.sekahama.club
  document_root_user: kyoko
  log_dir: /var/log/h2o
  run_dir: /run/h2o
  version: 'v1.4.4'
logrotate:
  app_log_dir: /var/www/ikyusan.sekahama.club/ikyusan-api/shared/log
  rotate: 1
mysql:
  client_only: true
